CREATE DATABASE AVIATION_INSIGHTS_DB;

USE DATABASE AVIATION_INSIGHTS_DB;

CREATE SCHEMA ANALYTICS;

USE SCHEMA ANALYTICS;

CREATE WAREHOUSE AVIATION_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE AVIATION_WH;

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID INTEGER PRIMARY KEY,
    YEAR INTEGER,
    MONTH INTEGER,
    DAY INTEGER,
    DAY_OF_WEEK INTEGER
);

CREATE OR REPLACE TABLE DIM_AIRLINE (
    AIRLINE_CODE STRING,
    AIRLINE_NAME STRING
);

CREATE OR REPLACE TABLE DIM_AIRPORT (
    AIRPORT_CODE STRING,
    AIRPORT STRING,
    CITY STRING,
    STATE STRING,
    LATITUDE FLOAT,
    LONGITUDE FLOAT
);

COPY INTO FACT_FLIGHTS
(
DATE_ID,
AIRLINE,
ORIGIN_AIRPORT,
DESTINATION_AIRPORT,
DISTANCE,
DEPARTURE_DELAY,
ARRIVAL_DELAY,
AIR_TIME,
ELAPSED_TIME,
DIVERTED,
CANCELLED,
CANCELLATION_REASON,
AIR_SYSTEM_DELAY,
SECURITY_DELAY,
AIRLINE_DELAY,
LATE_AIRCRAFT_DELAY,
WEATHER_DELAY
)
FROM
(
SELECT
TO_NUMBER(t.$1 || LPAD(t.$2,2,'0') || LPAD(t.$3,2,'0')),
t.$5,
t.$8,
t.$9,
t.$18,
t.$12,
t.$23,
t.$17,
t.$16,
t.$24,
t.$25,
t.$26,
t.$27,
t.$28,
t.$29,
t.$30,
t.$31
FROM @aviation_stage/fact_flights_full_year.csv t
)
FILE_FORMAT = (
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY='"'
)
ON_ERROR='ABORT_STATEMENT';

USE DATABASE AVIATION_INSIGHTS_DB;

USE SCHEMA ANALYTICS;

USE WAREHOUSE AVIATION_WH;

show tables;

CREATE OR REPLACE STAGE aviation_stage
URL='azure://aviationinsightslake.blob.core.windows.net/gold'
CREDENTIALS=(AZURE_SAS_TOKEN='sp=rl&st=2026-03-15T18:07:44Z&se=2026-07-22T02:22:44Z&spr=https&sv=2024-11-04&sr=c&sig=1QyS1AnCn4zHzMKzHLny0dYDJu2YuMbuQ42GZU5HLI0%3D')
FILE_FORMAT=(TYPE=CSV SKIP_HEADER=1);

LIST @aviation_stage;

//Flight overview
CREATE OR REPLACE VIEW VW_FLIGHT_OVERVIEW AS
SELECT 
    COUNT(*) AS TOTAL_FLIGHTS,

    SUM(CASE WHEN ARRIVAL_DELAY > 0 THEN 1 ELSE 0 END) AS TOTAL_DELAYED_FLIGHTS,

    SUM(CASE WHEN CANCELLED = 1 THEN 1 ELSE 0 END) AS TOTAL_CANCELLED,

    SUM(CASE WHEN DIVERTED = 1 THEN 1 ELSE 0 END) AS TOTAL_DIVERTED,

    ROUND(AVG(ARRIVAL_DELAY),2) AS AVG_ARRIVAL_DELAY,

    -- On-Time Performance %
    ROUND(
        SUM(CASE WHEN ARRIVAL_DELAY <= 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
    2) AS ON_TIME_PERCENTAGE

FROM FACT_FLIGHTS;

//Flights by airline
CREATE OR REPLACE VIEW VW_FLIGHTS_BY_AIRLINE AS
SELECT 
a.AIRLINE_NAME,
COUNT(*) AS TOTAL_FLIGHTS,
ROUND(AVG(f.ARRIVAL_DELAY),2) AS AVG_DELAY,
SUM(CASE WHEN f.CANCELLED = 1 THEN 1 ELSE 0 END) AS TOTAL_CANCELLED
FROM FACT_FLIGHTS f
JOIN DIM_AIRLINE a
ON f.AIRLINE = a.AIRLINE_CODE
GROUP BY a.AIRLINE_NAME
ORDER BY TOTAL_FLIGHTS DESC;

//Monthly trends
CREATE OR REPLACE VIEW VW_MONTHLY_TRENDS AS
SELECT 
d.YEAR,
d.MONTH,
d.MONTH_NAME,
COUNT(*) AS TOTAL_FLIGHTS,
ROUND(AVG(f.ARRIVAL_DELAY),2) AS AVG_DELAY,
SUM(CASE WHEN f.CANCELLED = 1 THEN 1 ELSE 0 END) AS TOTAL_CANCELLED
FROM FACT_FLIGHTS f
JOIN DIM_DATE d
ON f.DATE_ID = d.DATE_ID
GROUP BY d.YEAR, d.MONTH, d.MONTH_NAME
ORDER BY d.MONTH;

//Delay analysis
CREATE OR REPLACE VIEW VW_DELAY_ANALYSIS AS
SELECT 
ROUND(SUM(AIR_SYSTEM_DELAY)/60,2) AS AIR_SYSTEM_HOURS,
ROUND(SUM(SECURITY_DELAY)/60,2) AS SECURITY_HOURS,
ROUND(SUM(AIRLINE_DELAY)/60,2) AS AIRLINE_HOURS,
ROUND(SUM(LATE_AIRCRAFT_DELAY)/60,2) AS LATE_AIRCRAFT_HOURS,
ROUND(SUM(WEATHER_DELAY)/60,2) AS WEATHER_HOURS
FROM FACT_FLIGHTS;

//Airport traffic origin (departure)
CREATE OR REPLACE VIEW VW_AIRPORT_TRAFFIC AS
SELECT 
ap.AIRPORT,
ap.CITY,
COUNT(*) AS TOTAL_FLIGHTS
FROM FACT_FLIGHTS f
JOIN DIM_AIRPORT ap
ON f.ORIGIN_AIRPORT = ap.AIRPORT_CODE
GROUP BY ap.AIRPORT, ap.CITY
ORDER BY TOTAL_FLIGHTS DESC;

//Cancellation analysis
CREATE OR REPLACE VIEW VW_CANCELLATION_ANALYSIS AS
SELECT 
    CASE CANCELLATION_REASON
        WHEN 'A' THEN 'Airline'
        WHEN 'B' THEN 'Weather'
        WHEN 'C' THEN 'National Air System'
        WHEN 'D' THEN 'Security'
    END AS REASON,
    
    COUNT(*) AS TOTAL_CANCELLED_FLIGHTS

FROM FACT_FLIGHTS
WHERE CANCELLED = 1
GROUP BY CANCELLATION_REASON;

//On-time performance
CREATE OR REPLACE VIEW VW_ON_TIME_PERFORMANCE AS
SELECT 
COUNT(*) AS TOTAL_FLIGHTS,
SUM(CASE WHEN ARRIVAL_DELAY <= 0 THEN 1 ELSE 0 END) AS ON_TIME_FLIGHTS,
ROUND(
    SUM(CASE WHEN ARRIVAL_DELAY <= 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 
2) AS ON_TIME_PERCENTAGE
FROM FACT_FLIGHTS
WHERE CANCELLED = 0;

//Deley severity buckets
CREATE OR REPLACE VIEW VW_DELAY_BUCKETS AS
SELECT 
CASE 
    WHEN ARRIVAL_DELAY <= 0 THEN 'On Time'
    WHEN ARRIVAL_DELAY BETWEEN 1 AND 15 THEN 'Minor Delay'
    WHEN ARRIVAL_DELAY BETWEEN 16 AND 60 THEN 'Moderate Delay'
    ELSE 'Severe Delay'
END AS DELAY_CATEGORY,
COUNT(*) AS TOTAL_FLIGHTS
FROM FACT_FLIGHTS
WHERE CANCELLED = 0
GROUP BY DELAY_CATEGORY;

//Top delayed routes
CREATE OR REPLACE VIEW VW_TOP_DELAYED_ROUTES AS
SELECT 
f.ORIGIN_AIRPORT,
f.DESTINATION_AIRPORT,
COUNT(*) AS TOTAL_FLIGHTS,
ROUND(AVG(f.ARRIVAL_DELAY),2) AS AVG_DELAY
FROM FACT_FLIGHTS f
WHERE f.CANCELLED = 0
GROUP BY f.ORIGIN_AIRPORT, f.DESTINATION_AIRPORT
HAVING COUNT(*) > 100
ORDER BY AVG_DELAY DESC;

//cancellation rate by airline
CREATE OR REPLACE VIEW VW_CANCELLATION_RATE AS
SELECT 
a.AIRLINE_NAME,
COUNT(*) AS TOTAL_FLIGHTS,
SUM(CASE WHEN f.CANCELLED = 1 THEN 1 ELSE 0 END) AS CANCELLED_FLIGHTS,
ROUND(
    SUM(CASE WHEN f.CANCELLED = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 
2) AS CANCELLATION_RATE
FROM FACT_FLIGHTS f
JOIN DIM_AIRLINE a
ON f.AIRLINE = a.AIRLINE_CODE
GROUP BY a.AIRLINE_NAME
ORDER BY CANCELLATION_RATE DESC;

//Busiest day of week
CREATE OR REPLACE DYNAMIC TABLE VW_DAYWISE_TRAFFIC AS
SELECT 
d.DAY_NAME,
COUNT(*) AS TOTAL_FLIGHTS
FROM FACT_FLIGHTS f
JOIN DIM_DATE d
ON f.DATE_ID = d.DATE_ID
GROUP BY d.DAY_NAME, d.DAY_OF_WEEK
ORDER BY d.DAY_OF_WEEK;

//Average distance vs delay
CREATE OR REPLACE VIEW VW_DISTANCE_ANALYSIS AS
SELECT 
CASE 
    WHEN DISTANCE < 500 THEN 'Short Haul'
    WHEN DISTANCE BETWEEN 500 AND 1500 THEN 'Medium Haul'
    ELSE 'Long Haul'
END AS DISTANCE_CATEGORY,
ROUND(AVG(ARRIVAL_DELAY),2) AS AVG_DELAY
FROM FACT_FLIGHTS
GROUP BY DISTANCE_CATEGORY;

CREATE OR REPLACE DYNAMIC TABLE DT_MONTHLY_TRENDS
TARGET_LAG = '1 HOUR'
WAREHOUSE = AVIATION_WH
AS
SELECT 
d.YEAR,
d.MONTH,
d.MONTH_NAME,
COUNT(*) AS TOTAL_FLIGHTS,
ROUND(AVG(f.ARRIVAL_DELAY),2) AS AVG_DELAY
FROM FACT_FLIGHTS f
JOIN DIM_DATE d
ON f.DATE_ID = d.DATE_ID
GROUP BY d.YEAR, d.MONTH, d.MONTH_NAME;

CREATE OR REPLACE VIEW VW_DELAY_REASON_COUNT AS
SELECT 'Airline' AS REASON, SUM(AIRLINE_DELAY) AS TOTAL_DELAY FROM FACT_FLIGHTS
UNION ALL
SELECT 'Air System', SUM(AIR_SYSTEM_DELAY) FROM FACT_FLIGHTS
UNION ALL
SELECT 'Late Aircraft', SUM(LATE_AIRCRAFT_DELAY) FROM FACT_FLIGHTS
UNION ALL
SELECT 'Weather', SUM(WEATHER_DELAY) FROM FACT_FLIGHTS
UNION ALL
SELECT 'Security', SUM(SECURITY_DELAY) FROM FACT_FLIGHTS;

show views;

SELECT * FROM VW_FLIGHT_OVERVIEW;
SELECT * FROM VW_FLIGHTS_BY_AIRLINE;
SELECT * FROM VW_MONTHLY_TRENDS;
SELECT * FROM VW_DELAY_ANALYSIS;
SELECT * FROM VW_AIRPORT_TRAFFIC;
SELECT * FROM VW_CANCELLATION_ANALYSIS;
SELECT * FROM VW_ON_TIME_PERFORMANCE;
SELECT * FROM VW_DELAY_BUCKETS;
SELECT * FROM VW_TOP_DELAYED_ROUTES;
SELECT * FROM VW_CANCELLATION_RATE;
SELECT * FROM VW_DAYWISE_TRAFFIC;
SELECT * FROM VW_DISTANCE_ANALYSIS;
SELECT * FROM DT_MONTHLY_TRENDS;
SELECT * FROM VW_DELAY_REASON_COUNT;

CREATE OR REPLACE VIEW VW_DELAY_REASON_COUNT AS
SELECT d.MONTH, 'Late Aircraft' AS REASON, COUNT(*) AS TOTAL_DELAY
FROM FACT_FLIGHTS f JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
WHERE LATE_AIRCRAFT_DELAY > 0
GROUP BY d.MONTH

UNION ALL

SELECT d.MONTH, 'Air System', COUNT(*)
FROM FACT_FLIGHTS f JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
WHERE AIR_SYSTEM_DELAY > 0
GROUP BY d.MONTH

UNION ALL

SELECT d.MONTH, 'Airline', COUNT(*)
FROM FACT_FLIGHTS f JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
WHERE AIRLINE_DELAY > 0
GROUP BY d.MONTH

UNION ALL

SELECT d.MONTH, 'Weather', COUNT(*)
FROM FACT_FLIGHTS f JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
WHERE WEATHER_DELAY > 0
GROUP BY d.MONTH

UNION ALL

SELECT d.MONTH, 'Security', COUNT(*)
FROM FACT_FLIGHTS f JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
WHERE SECURITY_DELAY > 0
GROUP BY d.MONTH;

CREATE OR REPLACE VIEW VW_DELAY_REASON_AVG AS
SELECT 
    d.MONTH,
    'Late Aircraft' AS REASON, 
    ROUND(AVG(LATE_AIRCRAFT_DELAY),2) AS AVG_DELAY
FROM FACT_FLIGHTS f
JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
WHERE LATE_AIRCRAFT_DELAY > 0
GROUP BY d.MONTH

UNION ALL

SELECT 
    d.MONTH,
    'Air System', 
    ROUND(AVG(AIR_SYSTEM_DELAY),2)
FROM FACT_FLIGHTS f
JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
WHERE AIR_SYSTEM_DELAY > 0
GROUP BY d.MONTH

UNION ALL

SELECT 
    d.MONTH,
    'Airline', 
    ROUND(AVG(AIRLINE_DELAY),2)
FROM FACT_FLIGHTS f
JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
WHERE AIRLINE_DELAY > 0
GROUP BY d.MONTH

UNION ALL

SELECT 
    d.MONTH,
    'Weather', 
    ROUND(AVG(WEATHER_DELAY),2)
FROM FACT_FLIGHTS f
JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
WHERE WEATHER_DELAY > 0
GROUP BY d.MONTH

UNION ALL

SELECT 
    d.MONTH,
    'Security', 
    ROUND(AVG(SECURITY_DELAY),2)
FROM FACT_FLIGHTS f
JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
WHERE SECURITY_DELAY > 0
GROUP BY d.MONTH;

CREATE OR REPLACE VIEW VW_BOTTOM_10_CARRIERS AS
SELECT 
    d.MONTH,
    f.AIRLINE AS AIRLINE_CODE,
    COUNT(*) AS TOTAL_DELAYED_FLIGHTS

FROM FACT_FLIGHTS f
JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID

WHERE f.ARRIVAL_DELAY > 0

GROUP BY d.MONTH, f.AIRLINE

QUALIFY ROW_NUMBER() OVER (
    PARTITION BY d.MONTH
    ORDER BY TOTAL_DELAYED_FLIGHTS DESC
) <= 10;

CREATE OR REPLACE VIEW VW_TOP_10_CARRIERS AS
SELECT 
    d.MONTH,
    f.AIRLINE AS AIRLINE_CODE,
    COUNT(*) AS TOTAL_DELAYED_FLIGHTS

FROM FACT_FLIGHTS f
JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID

WHERE f.ARRIVAL_DELAY > 0

GROUP BY d.MONTH, f.AIRLINE

QUALIFY ROW_NUMBER() OVER (
    PARTITION BY d.MONTH
    ORDER BY TOTAL_DELAYED_FLIGHTS ASC
) <= 10;

CREATE OR REPLACE VIEW VW_MONTHLY_TRENDS AS
SELECT 
    d.YEAR,
    d.MONTH,
    
    -- Proper ordered month name
    CASE d.MONTH
        WHEN 1 THEN 'Jan'
        WHEN 2 THEN 'Feb'
        WHEN 3 THEN 'Mar'
        WHEN 4 THEN 'Apr'
        WHEN 5 THEN 'May'
        WHEN 6 THEN 'Jun'
        WHEN 7 THEN 'Jul'
        WHEN 8 THEN 'Aug'
        WHEN 9 THEN 'Sep'
        WHEN 10 THEN 'Oct'
        WHEN 11 THEN 'Nov'
        WHEN 12 THEN 'Dec'
    END AS MONTH_NAME,

    COUNT(*) AS TOTAL_FLIGHTS,
    ROUND(AVG(f.ARRIVAL_DELAY),2) AS AVG_DELAY,
    SUM(CASE WHEN f.CANCELLED = 1 THEN 1 ELSE 0 END) AS TOTAL_CANCELLED

FROM FACT_FLIGHTS f
JOIN DIM_DATE d
ON f.DATE_ID = d.DATE_ID

GROUP BY d.YEAR, d.MONTH
ORDER BY d.MONTH;

CREATE OR REPLACE VIEW VW_AIRPORT_TRAFFIC AS
SELECT 
    d.MONTH,
    ap.AIRPORT_CODE AS AIRPORT,
    ap.CITY,

    COUNT(*) AS TOTAL_FLIGHTS,

    SUM(CASE WHEN f.ARRIVAL_DELAY > 0 THEN 1 ELSE 0 END) AS TOTAL_DELAYED_FLIGHTS,

    ROUND(
        SUM(CASE WHEN f.ARRIVAL_DELAY > 0 THEN 1 ELSE 0 END) 
        / COUNT(*) * 100,
    2) AS DELAY_RATE

FROM FACT_FLIGHTS f
JOIN DIM_AIRPORT ap ON f.ORIGIN_AIRPORT = ap.AIRPORT_CODE
JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID

GROUP BY 
    d.MONTH,
    ap.AIRPORT_CODE,
    ap.CITY

QUALIFY ROW_NUMBER() OVER (
    PARTITION BY d.MONTH
    ORDER BY TOTAL_DELAYED_FLIGHTS DESC
) <= 5;

CREATE OR REPLACE VIEW VW_AIRPORT_MAP AS
SELECT 
    d.MONTH,
    ap.AIRPORT AS AIRPORT_CODE,
    ap.CITY,
    ap.LATITUDE,
    ap.LONGITUDE,

    COUNT(*) AS TOTAL_FLIGHTS,

    SUM(CASE WHEN f.ARRIVAL_DELAY > 0 THEN 1 ELSE 0 END) AS TOTAL_DELAYED_FLIGHTS

FROM FACT_FLIGHTS f
JOIN DIM_AIRPORT ap ON f.ORIGIN_AIRPORT = ap.AIRPORT_CODE
JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID

GROUP BY 
    d.MONTH,
    ap.AIRPORT,
    ap.CITY,
    ap.LATITUDE,
    ap.LONGITUDE

QUALIFY ROW_NUMBER() OVER (
    PARTITION BY d.MONTH
    ORDER BY TOTAL_DELAYED_FLIGHTS DESC
) <= 10;

CREATE OR REPLACE VIEW VW_FLIGHT_OVERVIEW AS
SELECT 
    d.MONTH,

    COUNT(*) AS TOTAL_FLIGHTS,

    SUM(CASE WHEN ARRIVAL_DELAY > 0 THEN 1 ELSE 0 END) AS TOTAL_DELAYED_FLIGHTS,

    SUM(CASE WHEN CANCELLED = 1 THEN 1 ELSE 0 END) AS TOTAL_CANCELLED,

    SUM(CASE WHEN DIVERTED = 1 THEN 1 ELSE 0 END) AS TOTAL_DIVERTED,

    ROUND(AVG(ARRIVAL_DELAY),2) AS AVG_ARRIVAL_DELAY,

    ROUND(
        SUM(CASE WHEN ARRIVAL_DELAY <= 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
    2) AS ON_TIME_PERCENTAGE

FROM FACT_FLIGHTS f
JOIN DIM_DATE d
ON f.DATE_ID = d.DATE_ID

GROUP BY d.MONTH;

CREATE OR REPLACE VIEW VW_MONTH_DIM AS
SELECT DISTINCT 
    MONTH,
    CASE MONTH
        WHEN 1 THEN 'Jan'
        WHEN 2 THEN 'Feb'
        WHEN 3 THEN 'Mar'
        WHEN 4 THEN 'Apr'
        WHEN 5 THEN 'May'
        WHEN 6 THEN 'Jun'
        WHEN 7 THEN 'Jul'
        WHEN 8 THEN 'Aug'
        WHEN 9 THEN 'Sep'
        WHEN 10 THEN 'Oct'
        WHEN 11 THEN 'Nov'
        WHEN 12 THEN 'Dec'
    END AS MONTH_NAME
FROM DIM_DATE;